USE MASTER
CREATE DATABASE "QLBanHang";

GO
USE QLBanHang
GO

CREATE TABLE HoaDon(
MaHD CHAR(4) NOT NULL PRIMARY KEY,
NgayLap DATE NULL,
MaKH CHAR(4) NULL,
NguoiLap VARCHAR(10) NULL,
);

CREATE TABLE HoaDonChiTiet(
	MaHD CHAR(4) NOT NULL,
	MaSP CHAR(4) NOT NULL,
	SoLuongMua INT NULL,

	PRIMARY KEY(MaHD, MaSP),
);

CREATE TABLE KhachHang(
	MaKH CHAR(4) NOT NULL PRIMARY KEY,
	TenKH NVARCHAR(50) NULL,
	SoDT VARCHAR(12) NULL,
	DiaChi NVARCHAR(50) NULL,
);

CREATE TABLE LoaiSanPham(
	MaLoai CHAR(3) NOT NULL PRIMARY KEY,
	TenLoai NVARCHAR(50) NOT NULL,
);

CREATE TABLE NguoiDung(
	TenDangNhap VARCHAR(10) NOT NULL PRIMARY KEY,
	MatKhau VARCHAR(10) NOT NULL,
	HoTen NVARCHAR(50) NOT NULL,
);

CREATE TABLE SanPham(
	MaSP CHAR(4) NOT NULL PRIMARY KEY,
	TenSP NVARCHAR(50) NOT NULL,
	MaLoai CHAR(3) NULL,
	SoLuong INT NULL,
	DonGia INT NULL,
);

ALTER TABLE HoaDon ADD FOREIGN KEY(MaKH) REFERENCES KhachHang(MaKH);
ALTER TABLE HoaDonChiTiet ADD FOREIGN KEY(MaHD) REFERENCES HoaDon(MaHD);
ALTER TABLE HoaDonChiTiet ADD FOREIGN KEY(MaSP) REFERENCES SanPham(MaSP);
ALTER TABLE SanPham ADD FOREIGN KEY(MaLoai) REFERENCES LoaiSanPham(MaLoai);
